name: CI

on:
    push:
        branches: [ "main" ]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
                cache: 'pip'
            - name: Create virtual environment
              run: python3 -m venv --upgrade-deps .venv

            - name: Install project dependencies
              run: .venv/bin/pip install .[dev]

            - name: Run tests
              run: make test

            - name: Run type check
              run: make mypy

            - name: Run black check
              run: make format-check
